provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  slack:
    lang: golang-middleware
    handler: ./slack
    image: ${OWNER:-alexellis2}:/slack:${TAG:-latest}
    labels:
      com.openfaas.scale.zero: false
    environment:
      slack_url: "https://docs.openfaas.com/community"

  zoom:
    lang: golang-middleware
    handler: ./slack
    image: ${OWNER:-alexellis2}:/slack:${TAG:-latest}
    labels:
      com.openfaas.scale.zero: false
    environment:
      slack_url: "https://zoom.us/j/4215401314"

  insiders:
    lang: golang-middleware
    handler: ./slack
    image: ${OWNER:-alexellis2}:/slack:${TAG:-latest}
    labels:
      com.openfaas.scale.zero: false
    environment:
      slack_url: "https://github.com/users/alexellis/sponsorship"

  cal:
    lang: golang-middleware
    handler: ./slack
    image: ${OWNER:-alexellis2}:/slack:${TAG:-latest}
    labels:
      com.openfaas.scale.zero: false
    environment:
      slack_url: "https://calendly.com/alexellis"

  join-welcome:
    lang: python3-http
    handler: ./join-welcome
    image: ${OWNER:-alexellis2}/join-welcome:${TAG:-latest}
    labels:
      com.openfaas.scale.zero: false
    environment:
      write_debug: false
      read_debug: false
      combine_output: false
      content_type: application/json
      target_channel: "C4XCQR8TY"
      log_env: "0"
    secrets:
      - cloud-functions-secrets

  external-ip:
    lang: golang-middleware
    handler: ./external-ip
    image: ${OWNER:-alexellis2}/external-ip:${TAG:-latest}

configuration:
  templates:
    - name: golang-middleware
